20/10/20 (12:57:32) | ERROR: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2738, in _collect_temps
    if hasattr(entry, "high") and entry.high > 1: cls.cpu_temp_high = round(entry.high)
TypeError: '>' not supported between instances of 'NoneType' and 'int'
20/10/20 (13:04:01) | ERROR: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2738, in _collect_temps
    if hasattr(entry, "high") and entry.high > 1: cls.cpu_temp_high = round(entry.high)
TypeError: '>' not supported between instances of 'NoneType' and 'int'
23/10/20 (15:45:15) | ERROR: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2738, in _collect_temps
    if hasattr(entry, "high") and entry.high > 1: cls.cpu_temp_high = round(entry.high)
TypeError: '>' not supported between instances of 'NoneType' and 'int'
23/10/20 (15:46:52) | ERROR: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2738, in _collect_temps
    if hasattr(entry, "high") and entry.high > 1: cls.cpu_temp_high = round(entry.high)
TypeError: '>' not supported between instances of 'NoneType' and 'int'
01/11/20 (19:13:25) | ERROR: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2738, in _collect_temps
    if hasattr(entry, "high") and entry.high > 1: cls.cpu_temp_high = round(entry.high)
TypeError: '>' not supported between instances of 'NoneType' and 'int'
03/11/20 (19:53:39) | ERROR: 2
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2787, in _collect_temps
    cls.cpu_temp[x+1].append(core_dict[z])
KeyError: 2
22/12/20 (22:06:40) | ERROR: [Errno 2] No such file or directory: '/home/josuer08/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/josuer08/.config/bpytop/themes'
22/12/20 (22:09:31) | ERROR: [Errno 2] No such file or directory: '/home/josuer08/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/josuer08/.config/bpytop/themes'
19/01/21 (16:18:23) | ERROR: [Errno 2] No such file or directory: '/home/josuer08/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1266, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/josuer08/.config/bpytop/themes'
